#!/usr/bin/env bash

cd "$(dirname "$(realpath "$0")")"

backend="$(impl/detect-backend)" || exit 1

function backend {
  "impl/backend-$backend" "$@"
}

#  top_screen_touch_panel="/sys/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-1/i2c-ELAN9008:00/0018:04F3:425B.0007/"
bottom_screen_touch_panel="/sys/devices/pci0000:00/0000:00:19.1/i2c_designware.3/i2c-4/i2c-ELAN9009:00/0018:04F3:425A.0008/"

# 3k model
backlight=card1-eDP-2-backlight

# 1080p model
#backlight=card1-eDP-2-backlight

function suenv {
  sudo /usr/bin/env "$@"
}

function get-orientation {
  gdbus call --system --dest net.hadess.SensorProxy --object-path /net/hadess/SensorProxy --method org.freedesktop.DBus.Properties.Get net.hadess.SensorProxy AccelerometerOrientation | sed "s/.*<'\([^']*\)'>.*/\1/"
}

function keyboard-is-attached {
  lsusb|grep 0b05:1b2c
}

function set-bottom-screen-touch-inhibition {
  echo "$1"|suenv tee $bottom_screen_touch_panel/input/input*/inhibited
}

case "$1" in
  watch-displays)
    "$0" "$(get-orientation)"
    while inotifywait -e attrib /dev/bus/usb/*/ ; do
      if ! backend external-display-connected; then
        "$0" "$(get-orientation)"
      fi
    done
    ;;
  set-displays)
    if ! backend external-display-connected; then
      "$0" normal
    fi
    ;;
  normal|bottom-up)
    if keyboard-is-attached; then
      "$0" top
    else
      "$0" both
    fi
    ;;
  top)
    backend set-layout top
    set-bottom-screen-touch-inhibition 1
    ;;
  both)
    backend set-layout both
    set-bottom-screen-touch-inhibition 0
    ;;
  bottom)
    backend set-layout bottom
    set-bottom-screen-touch-inhibition 0
    ;;
  left-up)
    backend set-layout left-up
    set-bottom-screen-touch-inhibition 0
    ;;
  right-up)
    backend set-layout right-up
    set-bottom-screen-touch-inhibition 0
    ;;
  status-internal)
    backend status-internal
    ;;
  status)
    backend active-external-displays|grep -vE "^$"|sed -z "s/\n/+/g"
    "$0" status-internal
    ;;
  toggle)
    if [ "$(backend status-internal)" = both ]; then
      "$0" top
    else
      "$0" both
    fi
    ;;
  set-tablet-mapping)
    backend map-inputs
    ;;
  toggle-bottom-touch)
    backend toggle-bottom-touch
    ;;
  bat-limit)
    echo "${2:-80}" | suenv tee /sys/class/power_supply/BAT0/charge_control_end_threshold
    ;;
  sync-backlight)
    cat "/sys/class/backlight/intel_backlight/brightness" |
      suenv tee /sys/class/backlight/$backlight/brightness
    ;;
  set-kb-backlight)
    suenv python3 bk.py "$2"
    ;;
  watch-backlight)
    "$0" sync-backlight
    while inotifywait -e modify /sys/class/backlight/intel_backlight/brightness ; do
      "$0" sync-backlight
    done
    ;;
  watch-rotation)
    monitor-sensor --accel |
      stdbuf -oL grep orientation |
      stdbuf -oL cut -d: -f2 |
      stdbuf -oL sed 's/[ )]//g' |
      xargs -I '{}' stdbuf -oL "$0" '{}'
    ;;
  *) echo "Usage: duo <top|bottom|both|set-displays|toggle|status|set-tablet-mapping|bat-limit|sync-backlight|set-kb-backlight|watch-backlight|watch-rotation|watch-displays>"
esac
